/**
 * Skill icons — one drawn tile per skill, in the tradition of the old
 * browser brawlers: a bevelled olive plaque with a single bold symbol on it.
 *
 * Every grid is 16x16. Characters pick a colour, not a shape, so the same
 * symbol reads at 24px in a chip and at 64px on a level-up card:
 *   #  ink      o  shade      *  light
 *   r  blood    g  gold       n  green      b  blue      w  bone
 *   h  wood
 */

const ART: Record<string, string[]> = {
  /* ---------------- boons: always-on, so they read as worn kit ------------- */
  bronze_hide: [
    "................",
    "..############..",
    ".#ssssssssssss#.",
    ".#s##ss##ss##s#.",
    ".#ssssssssssss#.",
    ".#s##ss##ss##s#.",
    ".#ssssssssssss#.",
    ".#s##ss##ss##s#.",
    ".#ssssssssssss#.",
    "..#ssssssssss#..",
    "..#ssss##ssss#..",
    "...#ssssssss#...",
    "....#ssssss#....",
    ".....#ssss#.....",
    "......####......",
    "................",
  ],
  winged_heels: [
    "................",
    "................",
    "*...............",
    "**..............",
    "***.....####....",
    "****...#ssss#...",
    "*****..#ssss#...",
    "****...#ssss#...",
    "***....#ssss#...",
    "**.....#ssss#...",
    "*......#sssss#..",
    "......#ssssss#..",
    ".....#ssssssss#.",
    "....#ssssssssss#",
    "....############",
    "................",
  ],
  eagle_eye: [
    "................",
    "................",
    ".....######.....",
    "...##******##...",
    "..#**********#..",
    ".#***bbbbbb***#.",
    ".#**bbb##bbb**#.",
    "#***bb####bb***#",
    "#***bb####bb***#",
    ".#**bbb##bbb**#.",
    ".#***bbbbbb***#.",
    "..#**********#..",
    "...##******##...",
    ".....######.....",
    "................",
    "................",
  ],
  hoplite_drill: [
    "................",
    ".....######.....",
    "...##gggggg##...",
    "..#gggggggggg#..",
    ".#gggggggggggg#.",
    "#ggggggssgggggg#",
    "#gggggssgssgggg#",
    "#ggggssgggssggg#",
    "#gggssgggggssgg#",
    "#ggssgggggggssg#",
    "#gggggggggggggg#",
    ".#gggggggggggg#.",
    "..#gggggggggg#..",
    "...##gggggg##...",
    ".....######.....",
    "................",
  ],
  pankration: [
    "................",
    "................",
    "...##.##.##.##..",
    "..#ss#ss#ss#ss#.",
    "..#sssssssssss#.",
    ".#sssssssssssss#",
    ".#s#ss#ss#ss#ss#",
    ".#sssssssssssss#",
    ".#sssssssssssss#",
    "#ss#ssssssssss#.",
    "#sss#sssssssss#.",
    "#ssssssssssss#..",
    ".#sssssssssss#..",
    "..#ssssssssss#..",
    "...##########...",
    "................",
  ],
  titan_grip: [
    ".####......####.",
    "#gggg#....#gggg#",
    "#ggggg#hh#ggggg#",
    "#ggggg#hh#ggggg#",
    ".#gggg#hh#gggg#.",
    "..####.hh.####..",
    ".......hh.......",
    "....########....",
    "...#ss#ss#ss#...",
    "...#ss#ss#ss#...",
    "...#ssssssss#...",
    "...#ssssssss#...",
    "....########....",
    ".......hh.......",
    ".......hh.......",
    "................",
  ],
  keen_edge: [
    "................",
    ".....*..........",
    "....*.*.......*.",
    ".....*.......*.*",
    "..............*.",
    "hhh#############",
    "hhh##***********",
    "hhh#############",
    "hhh###ooooooooo.",
    "....ooooooooo...",
    "................",
    ".....*..........",
    "....*.*.........",
    ".....*..........",
    "................",
    "................",
  ],
  serpent_reflex: [
    "................",
    ".....######.....",
    "...##########...",
    "..###*....*###..",
    "..###......###..",
    "..####.........#",
    "...######.......",
    ".....######.....",
    ".......######...",
    "#.........####..",
    ".###......###...",
    ".###*....*###...",
    "..##########....",
    "....######......",
    "................",
    "................",
  ],
  iron_wrists: [
    "................",
    "...##########...",
    "..o##########o..",
    "..o#g######g#o..",
    "..o##########o..",
    "..o#*######*#o..",
    "..o##########o..",
    "..o#g######g#o..",
    "..o##########o..",
    "..o##########o..",
    "..o#g######g#o..",
    "..o##########o..",
    "...o########o...",
    "....oooooooo....",
    "................",
    "................",
  ],
  marathon_lungs: [
    "................",
    ".......##.......",
    ".......##.......",
    "....########....",
    "..###..##..###..",
    ".####..##..####.",
    ".#####.##.#####.",
    ".######..######.",
    ".#####*..*#####.",
    ".#####....#####.",
    "..####....####..",
    "..###......###..",
    "...##......##...",
    "................",
    "................",
    "................",
  ],
  beast_bond: [
    "................",
    ".###.###.###.###",
    ".###.###.###.###",
    ".###.###.###.###",
    "................",
    "...##########...",
    "..############..",
    ".##############.",
    "################",
    "################",
    ".##############.",
    "..############..",
    "...##########...",
    ".....######.....",
    "................",
    "................",
  ],
  endless_quiver: [
    "....*..*..*.....",
    "...***.**.***...",
    "....#..#..#.....",
    "....#..#..#.....",
    "....#..#..#.....",
    "...##########...",
    "..o##########o..",
    "..o#*######*#o..",
    "..o##########o..",
    "..o##########o..",
    "..o#*######*#o..",
    "..o##########o..",
    "..o##########o..",
    "...o########o...",
    "....oooooooo....",
    "................",
  ],

  /* -------------- techniques: a moment of the fight, frozen --------------- */
  whirl_of_bronze: [
    "................",
    ".....######.....",
    "...####**####...",
    "..###......###..",
    ".###........###.",
    ".##..........##.",
    "###..........###",
    "##............##",
    "##............##",
    "###..........###",
    ".##..........##.",
    ".###........###.",
    "..###......###..",
    "...####..####...",
    ".....######.....",
    "................",
  ],
  shield_slam: [
    ".*............*.",
    "...##gggggg##...",
    "..#gggggggggg#..",
    ".#gggggggggggg#.",
    "#gggggggggggggg#",
    "#ggggggssgggggg#",
    "#gggggssgssgggg#",
    "#ggggssgggssggg#",
    "#gggssgggggssgg#",
    "#ggssgggggggssg#",
    "#gggggggggggggg#",
    ".#gggggggggggg#.",
    "..#gggggggggg#..",
    "...##gggggg##...",
    ".*...######...*.",
    "..*..........*..",
  ],
  perfect_riposte: [
    "o#o..........o#o",
    "o#o..........o#o",
    "o#*o........o*#o",
    ".o#o........o#o.",
    ".o#*o......o*#o.",
    "..o#o......o#o..",
    "..o#*o....o*#o..",
    "...o#o....o#o...",
    "...o#*o..o*#o...",
    "....o#o..o#o....",
    "....o#*oo*#o....",
    ".....o####o.....",
    ".....hhhhhh.....",
    "......hhhh......",
    "......oooo......",
    "................",
  ],
  hamstring: [
    ".....####.......",
    "....#ssss#......",
    "....#ssss#......",
    "....#ssss#......",
    "....#ssss#......",
    "....#ssss#......",
    "rr..#ssss#..rr..",
    ".rr.#ssss#.rr...",
    "..rr#ssss#rr....",
    "...r#ssss#r.....",
    "....#ssss#......",
    "....#ssss#......",
    "....#ssss#......",
    "....#sssss#.....",
    "....#ssssssss#..",
    ".....#########..",
  ],
  second_breath: [
    "................",
    "..rrrr....rrrr..",
    ".rrrrrr..rrrrrr.",
    "rrr*rrrrrrrrrrrr",
    "rr**rrrrrrrrrrrr",
    "rr*rrrrrrrrrrrrr",
    ".rrrrrrrrrrrrrr.",
    ".rrrrrrrrrrrrrr.",
    "..rrrrrrrrrrrr..",
    "...rrrrrrrrrr...",
    "....rrrrrrrr....",
    ".....rrrrrr.....",
    "......rrrr......",
    ".......rr.......",
    "................",
    "................",
  ],
  rope_and_net: [
    "................",
    ".##..##..##..##.",
    ".##..##..##..##.",
    "################",
    ".##..##..##..##.",
    ".##..##..##..##.",
    "################",
    ".##..##..##..##.",
    ".##..##..##..##.",
    "################",
    ".##..##..##..##.",
    ".##..##..##..##.",
    "################",
    ".##..##..##..##.",
    "................",
    "................",
  ],
  skyfall: [
    ".......##.......",
    ".......##.......",
    ".......##.......",
    ".......##.......",
    ".......##.......",
    ".......##.......",
    ".......##.......",
    ".*.....##.....*.",
    "..*....##....*..",
    "o##o...##...o##o",
    ".o##o..##..o##o.",
    "..o##o.##.o##o..",
    "...o##o##o##o...",
    "....o##o##o.....",
    ".....o###o......",
    "......o#o.......",
  ],
  twin_fangs: [
    "................",
    ".####......####.",
    ".####......####.",
    ".####......####.",
    ".o###......###o.",
    ".o###......###o.",
    "..o##......##o..",
    "..o##......##o..",
    "..o#*......*#o..",
    "...o#......#o...",
    "...o#......#o...",
    "....#......#....",
    "....#......#....",
    ".....o....o.....",
    "................",
    "................",
  ],
  beasts_fury: [
    "rr..rr..rr......",
    "rr..rr..rr......",
    ".rr..rr..rr.....",
    ".rr..rr..rr.....",
    "..rr..rr..rr....",
    "..rr..rr..rr....",
    "...rr..rr..rr...",
    "...rr..rr..rr...",
    "....rr..rr..rr..",
    "....rr..rr..rr..",
    ".....rr..rr..rr.",
    ".....rr..rr..rr.",
    "......rr..rr..rr",
    "......rr..rr..rr",
    ".......r...r...r",
    "................",
  ],
  stone_wall: [
    "................",
    "################",
    "#oooo#oooo#oooo#",
    "#oooo#oooo#oooo#",
    "################",
    "oo#oooo#oooo#ooo",
    "oo#oooo#oooo#ooo",
    "################",
    "#oooo#oooo#oooo#",
    "#oooo#oooo#oooo#",
    "################",
    "oo#oooo#oooo#ooo",
    "oo#oooo#oooo#ooo",
    "################",
    "................",
    "................",
  ],

  /* ------------- trumps: the big ones, so they carry gold ---------------- */
  wrath_of_herakles: [
    "....######......",
    "...########.....",
    "..#hh##hh##h#...",
    "..#hhhhhhhhh#...",
    "..##hh##hhh##...",
    "..#hhhhh##hh#...",
    "..#hh##hhhhh#...",
    "...#hhhhhhh#....",
    "....##hhh##.....",
    ".....#hhh#......",
    ".....#hhh#......",
    ".....#ooo#......",
    ".....#hhh#......",
    ".....#ooo#......",
    ".....#hhh#......",
    ".....#####......",
  ],
  aegis_of_dawn: [
    "g..g...gg...g..g",
    "..g.g..gg..g.g..",
    "...##ssssss##...",
    "..#ssssssssss#..",
    ".#ssssssssssss#.",
    "#ssssssggssssss#",
    "#sssssggsggssss#",
    "#ssssggsssggsss#",
    "#sssggsssssggss#",
    "#ssggsssssssggs#",
    "#ssssssssssssss#",
    ".#ssssssssssss#.",
    "..#ssssssssss#..",
    "...##ssssss##...",
    "..g.g..gg..g.g..",
    "g..g...gg...g..g",
  ],
  gorgons_glare: [
    ".n..n..n..n..n..",
    "nn.nn.nn.nn.nn..",
    ".nnnnnnnnnnnnn..",
    "..#sssssssss#...",
    "..#sssssssss#...",
    ".#sssssssssss#..",
    ".#ss##sss##ss#..",
    ".#ss##sss##ss#..",
    ".#sssssssssss#..",
    "..#ss#####ss#...",
    "..#sss###sss#...",
    "...#sssssss#....",
    "....#sssss#.....",
    ".....#####......",
    "................",
    "................",
  ],
  chirons_mending: [
    "................",
    ".......n........",
    "....nnnnnnn.....",
    "...nnnnnnnnn....",
    "....nnn.nnn.....",
    ".....n.h.n......",
    ".......h........",
    "...nnn.h.nnn....",
    "..nnnnnhnnnnn...",
    "...nnn.h.nnn....",
    ".......h........",
    ".......h........",
    ".......h........",
    "......ooo.......",
    "................",
    "................",
  ],
  hermes_rush: [
    "................",
    "................",
    "................",
    "..gg.......gg...",
    "..ggg......ggg..",
    "...ggg......ggg.",
    "....ggg......ggg",
    ".....gg.......gg",
    "....ggg......ggg",
    "...ggg......ggg.",
    "..ggg......ggg..",
    "..gg.......gg...",
    "................",
    "................",
    "................",
    "................",
  ],
  brontes_bolt: [
    ".......gggg.....",
    "......gggg......",
    ".....gggg.......",
    "....gggg........",
    "...gggg.........",
    "..gggggggg......",
    "...ggggggg......",
    "......gggg......",
    ".....gggg.......",
    "....gggg........",
    "...gggg.........",
    "..gggg..........",
    ".gggg...........",
    ".ggg............",
    ".gg.............",
    "................",
  ],
  cast_down: [
    ".............oo.",
    "............o##o",
    "...........o##o.",
    "..........o##o..",
    ".........o##o...",
    "........o##o....",
    ".......o##o.....",
    "....oo###o......",
    "....oohho.......",
    ".....hho........",
    "....hho.........",
    "...oo...........",
    "r...............",
    ".r..............",
    "..r.............",
    "................",
  ],
  moiras_thread: [
    ".......##.......",
    "......#ss#......",
    ".....#ssss#.....",
    "....#ssssss#....",
    "....#s####s#....",
    "....#ssssss#....",
    ".....#ssss#.....",
    "......#ss#......",
    ".......##.......",
    ".......##.......",
    "......#ss#......",
    ".....#ssss#.....",
    "....#ssssss#....",
    "....#s####s#....",
    ".....######.....",
    "................",
  ],
};

/**
 * Ink is warm near-black rather than pure black: on an olive plaque a true
 * black symbol punches a hole in the tile instead of sitting on it.
 */
const INK: Record<string, string> = {
  "#": "#2a2109",
  o: "#4a3d14",
  "*": "#fbf4d2",
  r: "#a92b1f",
  g: "#f0bc32",
  n: "#4f8c34",
  b: "#3f6fa8",
  w: "#f4efdb",
  h: "#7a4f24",
  s: "#d6ccae",
};

/** Merge each row's runs of one colour into a single rect. */
function rects(grid: string[]): Array<{ x: number; y: number; w: number; c: string }> {
  const out: Array<{ x: number; y: number; w: number; c: string }> = [];
  grid.forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      const ch = row[x]!;
      if (ch === ".") {
        x++;
        continue;
      }
      let w = 1;
      while (x + w < row.length && row[x + w] === ch) w++;
      out.push({ x, y, w, c: INK[ch] ?? INK["#"]! });
      x += w;
    }
  });
  return out;
}

const CACHE = new Map<string, ReturnType<typeof rects>>();
function shapeOf(id: string) {
  let r = CACHE.get(id);
  if (!r) {
    r = rects(ART[id] ?? ART["pankration"]!);
    CACHE.set(id, r);
  }
  return r;
}

export type SkillKind = "boon" | "technique" | "trump";

/**
 * A skill as a plaque. `flat` drops the frame for places that already have
 * one of their own, like a chip.
 */
export function SkillIcon({
  id,
  kind,
  size = 34,
  title,
}: {
  id: string;
  kind: SkillKind;
  size?: number;
  title?: string;
}) {
  const pad = Math.max(1, Math.round(size * 0.11));
  return (
    <span className={`skill-tile tile-${kind}`} style={{ width: size, height: size }} title={title}>
      <svg
        viewBox="0 0 16 16"
        width={size - pad * 2}
        height={size - pad * 2}
        shapeRendering="crispEdges"
        aria-hidden="true"
      >
        {shapeOf(id).map((r, i) => (
          <rect key={i} x={r.x} y={r.y} width={r.w} height={1} fill={r.c} />
        ))}
      </svg>
    </span>
  );
}
