import type { WeaponDef } from "../types.js";

/** Unarmed baseline (02-gdd-core.md §5.1). Pankration upgrades it. */
export const FISTS: WeaponDef = {
  id: "fists",
  name: "Fists",
  discipline: "cestus",
  dmg: 4,
  scaleStat: "might",
  scalePct: 60,
  interval: 240,
  reach: 0,
  mods: { combo: 5 },
  flavour: "A Champion is never helpless.",
};

/** The 24 launch weapons (02-gdd-core.md §5.2), numbers verbatim. */
export const WEAPONS: WeaponDef[] = [
  // --- Doru: the spear discipline (reach, counter) ---
  {
    id: "doru",
    name: "Doru",
    discipline: "doru",
    dmg: 12,
    scaleStat: "might",
    scalePct: 90,
    interval: 320,
    reach: 3,
    mods: { init: 20, counter: 15, acc: 5, block: 5 },
    flavour: "The measuring stick: pays for reach with middling pace.",
  },
  {
    id: "sarissa",
    name: "Sarissa",
    discipline: "doru",
    dmg: 15,
    scaleStat: "might",
    scalePct: 95,
    interval: 380,
    reach: 3,
    twoHanded: true,
    mods: { counter: 25, init: -40, acc: -5 },
    flavour: "The counter-wall incarnate; slow, shieldless, clumsy.",
  },
  {
    id: "trident",
    name: "Trident",
    discipline: "doru",
    dmg: 13,
    scaleStat: "might",
    scalePct: 85,
    interval: 330,
    reach: 2,
    mods: { counter: 12, disarm: 15, block: 5 },
    flavour: "Weapon control at the cost of one reach step.",
  },
  {
    id: "boar_spear",
    name: "Boar Spear",
    discipline: "doru",
    dmg: 14,
    scaleStat: "might",
    scalePct: 90,
    interval: 340,
    reach: 2,
    mods: { counter: 10, crit: 6 },
    special: "vsBeasts25",
    flavour: "The Beastmaster answer; ordinary vs beastless foes.",
  },

  // --- Xiphos: the blade discipline (balanced) ---
  {
    id: "xiphos",
    name: "Xiphos",
    discipline: "xiphos",
    dmg: 11,
    scaleStat: "might",
    scalePct: 80,
    interval: 280,
    reach: 1,
    mods: { acc: 5, block: 8, combo: 5 },
    flavour: "No weakness, no spike — the honest blade.",
  },
  {
    id: "kopis",
    name: "Kopis",
    discipline: "xiphos",
    dmg: 13,
    scaleStat: "might",
    scalePct: 85,
    interval: 300,
    reach: 1,
    mods: { crit: 8, block: -5 },
    flavour: "Chops harder, guards worse.",
  },
  {
    id: "makhaira",
    name: "Makhaira",
    discipline: "xiphos",
    dmg: 12,
    scaleStat: "might",
    scalePct: 80,
    interval: 290,
    reach: 1,
    mods: { block: 10, riposteDmgPct: 25 },
    flavour: "The duellist's blade; wants a Guarded plan.",
  },
  {
    id: "twin_xiphoi",
    name: "Twin Xiphoi",
    discipline: "xiphos",
    dmg: 8,
    scaleStat: "might",
    scalePct: 70,
    interval: 240,
    reach: 1,
    twoHanded: true,
    mods: { combo: 12, eva: 5, block: -5 },
    flavour: "A blender that forfeits the shield.",
  },

  // --- Cestus: the fist discipline (fast, combo) ---
  {
    id: "cestus",
    name: "Cestus",
    discipline: "cestus",
    dmg: 7,
    scaleStat: "might",
    scalePct: 65,
    interval: 220,
    reach: 0,
    mods: { combo: 15, eva: 5, acc: 5 },
    flavour: "Death by a thousand slaps.",
  },
  {
    id: "iron_cestus",
    name: "Iron Cestus",
    discipline: "cestus",
    dmg: 9,
    scaleStat: "might",
    scalePct: 75,
    interval: 250,
    reach: 0,
    mods: { combo: 10, disarm: 10, crit: 4 },
    flavour: "Heavier hands, slower hands.",
  },
  {
    id: "sphairai",
    name: "Sphairai",
    discipline: "cestus",
    dmg: 8,
    scaleStat: "might",
    scalePct: 70,
    interval: 230,
    reach: 0,
    mods: { combo: 12, crit: 8, acc: -5 },
    flavour: "Crit-fisher; swings wild.",
  },
  {
    id: "himantes",
    name: "Himantes",
    discipline: "cestus",
    dmg: 6,
    scaleStat: "might",
    scalePct: 60,
    interval: 210,
    reach: 0,
    mods: { combo: 18, eva: 8 },
    flavour: "Fastest weapon in the game; tickles.",
  },

  // --- Labrys: the great-axe discipline (slow, huge) ---
  {
    id: "labrys",
    name: "Labrys",
    discipline: "labrys",
    dmg: 24,
    scaleStat: "might",
    scalePct: 110,
    interval: 400,
    reach: 1,
    twoHanded: true,
    mods: { crit: 10, acc: -10, combo: -10, init: -60 },
    flavour: "Feast or famine, every swing.",
  },
  {
    id: "minoan_crusher",
    name: "Minoan Crusher",
    discipline: "labrys",
    dmg: 30,
    scaleStat: "might",
    scalePct: 120,
    interval: 460,
    reach: 1,
    twoHanded: true,
    mods: { crit: 12, acc: -15, init: -90 },
    flavour: "The biggest hit in AGOGE; may never land it.",
  },
  {
    id: "bipennis",
    name: "Bipennis",
    discipline: "labrys",
    dmg: 20,
    scaleStat: "might",
    scalePct: 105,
    interval: 380,
    reach: 1,
    twoHanded: true,
    mods: { crit: 8, acc: -5, disarm: 10 },
    flavour: "The 'light' heavy; batters weapons loose.",
  },
  {
    id: "olive_root_club",
    name: "Olive-Root Club",
    discipline: "labrys",
    dmg: 16,
    scaleStat: "might",
    scalePct: 95,
    interval: 340,
    reach: 1,
    special: "critDelay80",
    flavour: "The only one-handed Labrys — pairs with Aspis.",
  },

  // --- Akontia: thrown (Grace-scaled, armour-piercing, ammo-limited) ---
  {
    id: "akontion",
    name: "Akontion",
    discipline: "akontia",
    dmg: 10,
    scaleStat: "grace",
    scalePct: 100,
    interval: 300,
    reach: 0,
    ammo: 4,
    mods: { crit: 5 },
    flavour: "The standard javelin.",
  },
  {
    id: "kestros",
    name: "Kestros",
    discipline: "akontia",
    dmg: 7,
    scaleStat: "grace",
    scalePct: 90,
    interval: 260,
    reach: 0,
    ammo: 6,
    mods: { acc: 10 },
    flavour: "Reliable sting, modest venom.",
  },
  {
    id: "discus",
    name: "Discus",
    discipline: "akontia",
    dmg: 14,
    scaleStat: "grace",
    scalePct: 110,
    interval: 360,
    reach: 0,
    ammo: 3,
    mods: { acc: -5, crit: 6 },
    flavour: "Three big questions, then fists.",
  },
  {
    id: "peltast_blades",
    name: "Peltast Blades",
    discipline: "akontia",
    dmg: 5,
    scaleStat: "grace",
    scalePct: 80,
    interval: 220,
    reach: 0,
    ammo: 8,
    mods: { combo: 10 },
    flavour: "A chip stream; feeble singly.",
  },

  // --- Aspis: the shield discipline (off-hand, defence, disarmable) ---
  {
    id: "aspis",
    name: "Aspis",
    discipline: "aspis",
    dmg: 0,
    scaleStat: "might",
    scalePct: 0,
    interval: 0,
    reach: 0,
    mods: { block: 25, armour: 2, counter: 5, eva: -5 },
    flavour: "The standard: a wall you carry.",
  },
  {
    id: "pelte",
    name: "Pelte",
    discipline: "aspis",
    dmg: 0,
    scaleStat: "might",
    scalePct: 0,
    interval: 0,
    reach: 0,
    mods: { block: 15, armour: 1, eva: 5, init: 10 },
    flavour: "The skirmisher's shield; guards less, dances more.",
  },
  {
    id: "tower_of_dikte",
    name: "Tower of Dikte",
    discipline: "aspis",
    dmg: 0,
    scaleStat: "might",
    scalePct: 0,
    interval: 0,
    reach: 0,
    mods: { block: 32, armour: 4, eva: -10, intervalPct: 10, init: -40 },
    flavour: "Near-impregnable, near-immobile.",
  },
  {
    id: "spiked_aspis",
    name: "Spiked Aspis",
    discipline: "aspis",
    dmg: 0,
    scaleStat: "might",
    scalePct: 0,
    interval: 0,
    reach: 0,
    mods: { block: 20, armour: 2, riposteDmgPct: 30, counter: 5 },
    flavour: "Defence that bites back.",
  },
];

const byId = new Map<string, WeaponDef>([
  [FISTS.id, FISTS],
  ...WEAPONS.map((w) => [w.id, w] as const),
]);

export function weapon(id: string): WeaponDef {
  const w = byId.get(id);
  if (!w) throw new Error(`Unknown weapon: ${id}`);
  return w;
}
